services:
  smartdocs:
    build: .
    image: agentic

    ports:
      - "8501:8501"

    env_file:
      - ./app/.env

    volumes:
      - ./data:/app/data
      - ./chroma_db:/app/chroma_db
      - ./knowledge_base:/app/knowledge_base

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu